// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pa7sVod8bKytSwUDATE2VX
// Component: CtNWjoNnix
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import DisposableCollection3 from "../../DisposableCollection3"; // plasmic-import: s6pb6S-_rJoQ_/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_in_use_sparq_master_app.module.css"; // plasmic-import: pa7sVod8bKytSwUDATE2VX/projectcss
import sty from "./PlasmicBlog1.module.css"; // plasmic-import: CtNWjoNnix/css

export type PlasmicBlog1__VariantMembers = {};
export type PlasmicBlog1__VariantsArgs = {};
type VariantPropType = keyof PlasmicBlog1__VariantsArgs;
export const PlasmicBlog1__VariantProps = new Array<VariantPropType>();

export type PlasmicBlog1__ArgsType = {};
type ArgPropType = keyof PlasmicBlog1__ArgsType;
export const PlasmicBlog1__ArgProps = new Array<ArgPropType>();

export type PlasmicBlog1__OverridesType = {
  root?: p.Flex<"div">;
  disposableCollection3?: p.Flex<typeof DisposableCollection3>;
};

export interface DefaultBlog1Props {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBlog1__RenderFunc(props: {
  variants: PlasmicBlog1__VariantsArgs;
  args: PlasmicBlog1__ArgsType;
  overrides: PlasmicBlog1__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <DisposableCollection3
            data-plasmic-name={"disposableCollection3"}
            data-plasmic-override={overrides.disposableCollection3}
            className={classNames("__wab_instance", sty.disposableCollection3)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "disposableCollection3"],
  disposableCollection3: ["disposableCollection3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  disposableCollection3: typeof DisposableCollection3;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlog1__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlog1__VariantsArgs;
    args?: PlasmicBlog1__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBlog1__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBlog1__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBlog1__ArgProps,
          internalVariantPropNames: PlasmicBlog1__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBlog1__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlog1";
  } else {
    func.displayName = `PlasmicBlog1.${nodeName}`;
  }
  return func;
}

export const PlasmicBlog1 = Object.assign(
  // Top-level PlasmicBlog1 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    disposableCollection3: makeNodeComponent("disposableCollection3"),

    // Metadata about props expected for PlasmicBlog1
    internalVariantProps: PlasmicBlog1__VariantProps,
    internalArgProps: PlasmicBlog1__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicBlog1;
/* prettier-ignore-end */
