// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pa7sVod8bKytSwUDATE2VX
// Component: t1t7AWTaIOt
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import DisposableCollection3 from "../../DisposableCollection3"; // plasmic-import: s6pb6S-_rJoQ_/component
import SafeLeads from "../../SafeLeads"; // plasmic-import: 8AIy1r_kRBR85/component

import { useScreenVariants as useScreenVariantstrXlpJoOfOW4 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: TRXlpJoOf-oW4/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_in_use_sparq_master_app.module.css"; // plasmic-import: pa7sVod8bKytSwUDATE2VX/projectcss
import sty from "./PlasmicDisposableCollectionRemarketing.module.css"; // plasmic-import: t1t7AWTaIOt/css

export type PlasmicDisposableCollectionRemarketing__VariantMembers = {};
export type PlasmicDisposableCollectionRemarketing__VariantsArgs = {};
type VariantPropType =
  keyof PlasmicDisposableCollectionRemarketing__VariantsArgs;
export const PlasmicDisposableCollectionRemarketing__VariantProps =
  new Array<VariantPropType>();

export type PlasmicDisposableCollectionRemarketing__ArgsType = {};
type ArgPropType = keyof PlasmicDisposableCollectionRemarketing__ArgsType;
export const PlasmicDisposableCollectionRemarketing__ArgProps =
  new Array<ArgPropType>();

export type PlasmicDisposableCollectionRemarketing__OverridesType = {
  page?: p.Flex<"div">;
  disposableCollection3?: p.Flex<typeof DisposableCollection3>;
  safeLeads?: p.Flex<typeof SafeLeads>;
};

export interface DefaultDisposableCollectionRemarketingProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDisposableCollectionRemarketing__RenderFunc(props: {
  variants: PlasmicDisposableCollectionRemarketing__VariantsArgs;
  args: PlasmicDisposableCollectionRemarketing__ArgsType;
  overrides: PlasmicDisposableCollectionRemarketing__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantstrXlpJoOfOW4()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicDisposableCollectionRemarketing.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicDisposableCollectionRemarketing.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicDisposableCollectionRemarketing.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={
            PlasmicDisposableCollectionRemarketing.pageMetadata.description
          }
        />
        <meta
          key="og:description"
          property="og:description"
          content={
            PlasmicDisposableCollectionRemarketing.pageMetadata.description
          }
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={
            PlasmicDisposableCollectionRemarketing.pageMetadata.description
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        {(
          hasVariant(globalVariants, "screen", "desktopOnly")
            ? true
            : hasVariant(globalVariants, "screen", "largestMobile")
            ? true
            : hasVariant(globalVariants, "screen", "smallestMobile")
            ? true
            : true
        ) ? (
          <div
            data-plasmic-name={"page"}
            data-plasmic-override={overrides.page}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              sty.page
            )}
          >
            {true ? (
              <DisposableCollection3
                data-plasmic-name={"disposableCollection3"}
                data-plasmic-override={overrides.disposableCollection3}
                className={classNames(
                  "__wab_instance",
                  sty.disposableCollection3
                )}
              />
            ) : null}

            <SafeLeads
              data-plasmic-name={"safeLeads"}
              data-plasmic-override={overrides.safeLeads}
              className={classNames("__wab_instance", sty.safeLeads)}
            />
          </div>
        ) : null}
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  page: ["page", "disposableCollection3", "safeLeads"],
  disposableCollection3: ["disposableCollection3"],
  safeLeads: ["safeLeads"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  page: "div";
  disposableCollection3: typeof DisposableCollection3;
  safeLeads: typeof SafeLeads;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDisposableCollectionRemarketing__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDisposableCollectionRemarketing__VariantsArgs;
    args?: PlasmicDisposableCollectionRemarketing__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit< // Specify variants directly as props
    PlasmicDisposableCollectionRemarketing__VariantsArgs,
    ReservedPropsType
  > &
    /* Specify args directly as props*/ Omit<
      PlasmicDisposableCollectionRemarketing__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames:
            PlasmicDisposableCollectionRemarketing__ArgProps,
          internalVariantPropNames:
            PlasmicDisposableCollectionRemarketing__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDisposableCollectionRemarketing__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "page") {
    func.displayName = "PlasmicDisposableCollectionRemarketing";
  } else {
    func.displayName = `PlasmicDisposableCollectionRemarketing.${nodeName}`;
  }
  return func;
}

export const PlasmicDisposableCollectionRemarketing = Object.assign(
  // Top-level PlasmicDisposableCollectionRemarketing renders the root element
  makeNodeComponent("page"),
  {
    // Helper components rendering sub-elements
    disposableCollection3: makeNodeComponent("disposableCollection3"),
    safeLeads: makeNodeComponent("safeLeads"),

    // Metadata about props expected for PlasmicDisposableCollectionRemarketing
    internalVariantProps: PlasmicDisposableCollectionRemarketing__VariantProps,
    internalArgProps: PlasmicDisposableCollectionRemarketing__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Meet The Newest Flavor Diffuser",
      description: "Here's how to claim a free device!",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicDisposableCollectionRemarketing;
/* prettier-ignore-end */
